### ISSUE TITLE
Use with `srcSet`

### ISSUE THREAD

**Issue by DaveOrDead** [gvelo/babel-plugin-transform-react-jsx-img-import#2]
Hey, thanks for creating this, it's awesome!

One problem I had though when using it with React, is that it didn't seem to honour `srcSet`

e.g being able to do:
`<img srcSet="my-image@2x.png 2x" src="my-image.png"  alt="My alt text" />`.  It throws a 404 error saying it can't find the image.  Even though it works fine if I put it in the `src`.

I tried just `srcset`, but no joy there either. 

Am I missing something?

**Comment by gvelo** [comment]
Hi Dave, thanks for reporting on this, you are absolutely right about srcSet, this is not implemented yet. It's  going to be fixed in the next commit :-)

Thanks,
