### ISSUE TITLE
allow to override default transform behaviour

### ISSUE THREAD

**Issue by gvelo** [gvelo/babel-plugin-transform-react-jsx-img-import#3]
Allow to override transformation through a prefix like "!". 

for example,
`<img src="!/cdn/avatar.png" className="profile" />`

should be transformed to 
`<img src="/cdn/avatar.png" className="profile" />`

**Comment by kirkstrobeck** [comment]
My use-case was a base64 image

``` html
src="data:image/gif;base64,R0lGODlhEAAJAPAAAP///wAAACH5BAEAAAAALAAAAAAQAAkAAAJsIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCADs="
```

**Comment by gvelo** [comment]
Hi @kirkstrobeck, I post the #5 to track this one.
